# Generated by Django 2.2.7 on 2021-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/upload'),
        ),
    ]
