# Generated by Django 2.2.9 on 2022-06-06 01:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20220606_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
